set nocompatible                            " Forget legacy vi

source ~/.vim/vimrc-plugins.vim             " init plugins first thing
source ~/.vim/vimrc-settings.vim            " general vim customization

" language configs
source ~/.vim/vimrc-golang.vim              " Go config

