#!/bin/bash

json() {
  curl -s "https://go.dev/dl/?mode=json" \
  | jq -r '.[0].files[0].version'
}

txt() {
  curl -sSL 'https://go.dev/VERSION?m=text'
}


if [[ $# -eq 0 ]]; then
  if [[ $(command -v jq) ]]; then
    json
  else
    txt && echo
  fi
else
  "$@"
fi

