#!/bin/bash

# fail early
set -euo pipefail

declare -a DIRS=(
  "$HOME/.config/nvim/plugin"
  "$HOME/.local/share/nvim"
  "$HOME/.local/state/nvim"
  "$HOME/.cache/nvim"
)


for dir in "${DIRS[@]}"; do
  if [[ -d "$dir" ]]; then
    echo "Removing $dir"
    rm -rf "$dir"
  fi
done


