#!/usr/bin/env python3

from collections import namedtuple
from pathlib import Path
import argparse
import configparser
import os
import getpass
import re
import subprocess
import sys

# Python 3.7 required for subprocess handling of output capture
REQUIRED_VERSION = (3, 7)

DEFAULT_CONFIG_BASE = Path.home() / '.config'
DEFAULT_CONFIG_DIR = 'repo-tools'
DEFAULT_CONFIG_FILE = 'repos.cfg'

Repo = namedtuple('Repo', ['repo_url', 'upstream_url', 'directory', 'section'])


def fail(err_msg):
    print(err_msg, file=sys.stderr)
    sys.exit(1)


def resolve_config_file(conf_file=None, verify_exists=True):
    if conf_file:
        full_config = Path(conf_file)
    else:
        conf_base = os.getenv('XDG_CONFIG_HOME', DEFAULT_CONFIG_BASE.resolve())
        conf_path = Path(conf_base)
        full_config = conf_path / DEFAULT_CONFIG_DIR / DEFAULT_CONFIG_FILE

    config_dir = full_config.parent

    if verify_exists:
        if not config_dir.is_dir():
            fail(f"Configuration directory not found: {config_dir}")

        if not full_config.exists():
            fail(f"Configuration file not found: {full_config}")

    return full_config


def read_config(config_file):
    config = configparser.ConfigParser(
        interpolation=configparser.ExtendedInterpolation())
    config.read(config_file)
    return config


def build_repos(config):
    repos = [Repo(config[section].get('repo_url', vars=os.environ),
                  config[section].get('upstream_url', vars=os.environ),
                  Path(config[section].get('local_dir', vars=os.environ)),
                  section)
             for section in config
             if section != "DEFAULT"]

    return repos


def filter_repos(repos, filters):
    patterns = [re.compile(pat, re.IGNORECASE) for pat in filters]
    return [r for r in repos if any_match(patterns, r)]


def any_match(patterns, repo):
    # applying regex partial match against stringified named tuple seems to be good enough
    return any([pat.findall(str(repo)) for pat in patterns])


def init_config(config_file):
    if config_file:
        config_file = Path(config_file)
    else:
        config_file = resolve_config_file(verify_exists=False)

    config_dir = config_file.parent

    if config_file.exists():
        fail(f"Configuration file already exists: {config_file}")

    if not config_dir.is_dir():
        print(f"Creating directory {config_dir}")
        config_dir.mkdir(parents=True, exist_ok=True)

    config = configparser.ConfigParser()
    config['DEFAULT'] = {
        'git-base': 'git@github.com:' + getpass.getuser(),
        'git-base-private':  'git@git.home.lan:' + getpass.getuser()
    }
    config['notes'] = {
        'repo_url': '${git-base}/notes.git',
        'upstream_url': '${git-base-private}/notes.git',
        'local_dir': '${home}/Documents/notes'
    }

    print(f"Creating configuration file {config_file}")
    with open(config_file, 'w') as fout:
        config.write(fout)


def list_repos(repos, dirs_only=False):
    if dirs_only:
        layout = '{r.directory}'
    else:
        layout = '{status:8} {r.section:{width}} {r.directory}'
    width = max([len(r.section) for r in repos]) + 2

    for r in repos:
        if r.directory.is_dir():
            status = 'FOUND'
        else:
            status = 'MISSING'
        print(layout.format(r=r, status=status, width=width))


def clone_repos(repos, create_parents=False):
    for r in repos:
        if r.directory.is_dir():
            print(f"Already exists: {r.directory}\n")
            continue
        parent_dir = r.directory.parent
        if not parent_dir.is_dir():
            if create_parents:
                print(f"Creating parent directory: {parent_dir}")
                parent_dir.mkdir(parents=True, exist_ok=True)
            else:
                print(f"Parent directory not found: {parent_dir}")
                print(f"  skipping clone of {r.repo_url} to {r.directory}\n")
                continue

        print(f"Cloning {r.repo_url}")
        subprocess.run(['git',
                        'clone',
                        f"{r.repo_url}",
                        f"{r.directory.name}"],
                       cwd=parent_dir, check=True)
        set_upstream(r)
        print()


def verify_upstream(repos):
    for r in repos:
        set_upstream(r)


def set_upstream(repo):
    if not repo.directory.is_dir():
        return

    if not repo.upstream_url:
        print(f"Upstream URL not set for {repo.section}")
        return

    result = subprocess.run(['git', 'remote', '-v'], cwd=repo.directory, check=True,
                            capture_output=True, encoding='utf-8')
    if repo.upstream_url in result.stdout:
        print(
            f"Remote 'upstream' already set for {repo.section}: {repo.upstream_url}")
    else:
        print(
            f"Adding remote 'upstream' to {repo.section}: {repo.upstream_url}")
        subprocess.run(['git', 'remote', 'add', 'upstream', repo.upstream_url],
                       cwd=repo.directory, check=True)


def update_repos(repos):
    for r in repos:
        if r.directory.is_dir():
            print(f"Updating {r.directory.name} ...")
            subprocess.run(['git', 'pull'], cwd=r.directory, check=True)
        else:
            print(f"Not found on this machine: {r.directory}")
        print()


def latest_repos(repos):
    for r in repos:
        if r.directory.is_dir():
            print("#" * 80)
            print(f"Latest commmit of {r.directory}")
            subprocess.run(['git', 'log', '-n', '1'], cwd=r.directory, check=True)
            print()
        #else:
        #    print(f"Not found on this machine: {r.directory}")

def status_repos(repos, verbose=False):
    repo_clean_msg = 'working tree clean'

    for r in repos:
        if r.directory.is_dir():
            result = subprocess.run(['git', 'status'], cwd=r.directory, check=True,
                                    capture_output=True, encoding='utf-8')
            if repo_clean_msg in result.stdout:
                if verbose:
                    print(f"Status of {r.directory}")
                    print("  working tree clean\n")
            else:
                print("#" * 80)
                print(f"Status of {r.directory}")
                print(result.stdout, "\n")
        elif verbose:
            print(f"Not found on this machine: {r.directory}\n")


def sync_repos(repos, verbose=False):
    for r in repos:
        if r.directory.is_dir():
            print(f"Syncing {r.directory.name} ...")
            subprocess.run(['git', 'pull'], cwd=r.directory, check=True)
            subprocess.run(['git', 'push'], cwd=r.directory, check=True)
        else:
            print(f"Not found on this machine: {r.directory}")
        print()


def rollback_repos(repos, rollback_n):
    rollback_cmd = ['git', 'reset', '--hard', f'HEAD~{rollback_n}']
    if rollback_n < 1:
        print("Rollback value not specified (option '-r'). Showing dry run...\n")
        rollback_cmd = ['echo'] + rollback_cmd

    for r in repos:
        print(f"{r.directory}")
        if r.directory.is_dir():
            result = subprocess.run(['git', 'branch', '--show-current'], 
                                    cwd=r.directory, check=True,
                                    capture_output=True, encoding='utf-8')
            branch = result.stdout
            if "main" in branch or "master" in branch:
                print(f"rolling back {rollback_n} commits...")
                subprocess.run(rollback_cmd, cwd=r.directory, check=True)
            else:
                print(f"not currently on branch main/master")
            print()


def gen_clone_script(repos):
    for r in repos:
        parent_dir = r.directory.parent.resolve()
        checkout_dir = r.directory.resolve()
        print(f"# {r.section}")
        print(f"mkdir -p '{parent_dir}' && \\")
        print(f"  git clone '{r.repo_url}' '{checkout_dir}'\n")


def check_version():
    req_major, req_minor = REQUIRED_VERSION
    (major, minor, *details) = sys.version_info
    if major < req_major or (major == req_major and minor < req_minor):
        fail(f"This script requires Python v{req_major}.{req_minor} or later")


def main():
    check_version()
    cmds = 'init list ls clone last latest status stat sync update up pull upstream rollback script'.split()
    user_cfg = resolve_config_file(verify_exists=False)
    parser = argparse.ArgumentParser(
        description='A tool for cloning and updating multiple Git repos based on a personal configuration',
        epilog=f'User config location: {user_cfg}')
    parser.add_argument('cmd', metavar='subcommand', type=str,
                        nargs='?', default='list', choices=cmds,
                        help=f'task to run [{",".join(cmds)}]')
    parser.add_argument('filter',  metavar='filter', nargs='*',
                        help=f'repo selection filter (regex)')
    parser.add_argument('-c', '--config', metavar='config_file', type=str, dest='config_file',
                        nargs='?', help='path to configuration file')
    parser.add_argument('-d', '--dirsonly',  action='store_true', default=False,
                        dest='dirsonly',  help='print only directories in repos listing')
    parser.add_argument('-p', '--parents',  action='store_true',
                        dest='parents',  help='make parent directories as needed for clone')
    parser.add_argument('-r', '--rollback', type=int, metavar='N', dest='rollback',
                        nargs='?', default=0,  help='number of commits to rollback on main/master')
    parser.add_argument('-v', '--verbose',  action='store_true',
                        dest='verbose',  help="more verbose output on 'stat', etc.")
    args = parser.parse_args()

    # initializing a new config has a short execution path
    if args.cmd == "init":
        init_config(args.config_file)
        return

    config_file = resolve_config_file(args.config_file)
    config = read_config(config_file)
    repos = build_repos(config)

    if args.filter:
        repos = filter_repos(repos, args.filter)
        if not repos:
            fail(f"Zero repos match filters {args.filter}")

    #pprint(f"args: {args}")
    if args.cmd == "list" or args.cmd == "ls":
        list_repos(repos, args.dirsonly)
    elif args.cmd == "clone":
        clone_repos(repos, args.parents)
    # check for 'upstream' first so 'up' prefix is associated with 'update'
    elif args.cmd == "upstream":
        verify_upstream(repos)
    elif args.cmd.startswith("up") or args.cmd == "pull":
        update_repos(repos)
    elif args.cmd.startswith("la"):
        latest_repos(repos)
    elif args.cmd.startswith("stat"):
        status_repos(repos, args.verbose)
    elif args.cmd.startswith("sync"):
        sync_repos(repos, args.verbose)
    elif args.cmd.startswith("roll"):
        rollback_repos(repos, args.rollback)
    elif args.cmd == "script":
        gen_clone_script(repos)


if __name__ == "__main__":
    main()
