#!/usr/bin/env python3

from datetime import date, timedelta

target_date = date(2023, 9, 18)
milestone_days = [300, 250, 200, 150, 100, 60, 50, 40, 30, 20, 10]

def main():
    today = date.today()
    delta = target_date - today  # type datetime.timedelta
    print(f"{delta.days} days ({delta.days / 7:.1f} weeks) until {target_date}")

    print(f"\nMilestone Dates\n{'=' * 28}")
    for days in milestone_days:
        delta = timedelta(days=days)
        milestone = target_date - delta
        #print(f"{milestone} - {days} days")
        dstamp = milestone.strftime("%a %b %d, %Y")
        print(f"{days:3d} days - {dstamp}")


if __name__ == '__main__':
    main()


